services:
  - type: web
    name: dynamic-qr-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11